services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        ports:
            - '8000:80'
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=electric_bill_db
            - DB_USERNAME=laravel_user
            - DB_PASSWORD=laravel_password
        depends_on:
            - mysql
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost/api/users']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        volumes:
            - ./:/var/www/html

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: electric_bill_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        command: --default-authentication-plugin=mysql_native_password

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: laravel_phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root_password
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - '8080:80'
        depends_on:
            - mysql

volumes:
    mysql_data:
